<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<div id="m2fc" >
</div>


<script>
        window.m2fc = {
            layout: <?= /* @escapeNotVerified */ $block->getJsLayout() ?>,
            checkoutConfig: <?= /* @escapeNotVerified */ $block->getSerializedCheckoutConfig() ?>,
        };
        window.checkoutConfig = window.m2fc.checkoutConfig;
</script>
    
<script>

m2fc_bootstrap();

</script>
